In [60]:
import numpy as np
a = np.array([1,1])[:,None]
print(a)
b = np.array([1,2,3])
b_new = np.broadcast_to(b,(a.shape[0],b.shape[0]))
print(b_new)
print()
c = np.concatenate((a,b_new),axis=1)
print(c)

[[1]
 [1]]
[[1 2 3]
 [1 2 3]]

[[1 1 2 3]
 [1 1 2 3]]


In [66]:
LISTER = [[1,2,2], [1,2,3]]
a = np.array([[1,1],[1,2]])
print(a)
print()
print(b.shape[0])
b = np.array(LISTER)
c = np.concatenate((a,b),axis=1)
c

[[1 1]
 [1 2]]

2


array([[1, 1, 1, 2, 2],
       [1, 2, 1, 2, 3]])

In [3]:
# Importing library
import csv
  
# data to be written row-wise in csv fil
data = [['Geeks','happy'], [4], ['geeks !']]
  
# opening the csv file in 'w+' mode
file = open('g4g.csv', 'w+', newline ='')
  
# writing the data into the file
with file:    
    write = csv.writer(file)
    write.writerows(data)